tests: Fix compilation error with libsasl2
wocky-test-sasl-auth-server.c: In function ‘test_sasl_auth_server_new’:
wocky-test-sasl-auth-server.c:932:17: error: expected ‘)’ before ‘proc’
wocky-test-sasl-auth-server.c:932:22: error: expected ‘)’ before ‘(’ token
wocky-test-sasl-auth-server.c:932:30: error: expected ‘}’ before ‘test_sasl_server_auth_log’
wocky-test-sasl-auth-server.c:933:5: error: initialization from incompatible pointer type [-Werror]
wocky-test-sasl-auth-server.c:933:5: error: (near initialization for ‘callbacks[1].proc’) [-Werror]
wocky-test-sasl-auth-server.c: At top level: wocky-test-sasl-auth-server.c:886:1: error: ‘test_sasl_server_auth_log’
  defined but not used [-Werror=unused-function]