WockyXmppError: update to RFC 6120
The changes are:

* payment-required is removed;
* not-authorized is added to the schema (it was already defined in
  Wocky);
* policy-violation is added. XEP-0086 doesn't define an error code
  mapping for it, so I chose 406 "Not Acceptable".